apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arithmeticoperations.maths.tatacommunications.com
spec:
  group:  maths.tatacommunications.com
  version: "v1alpha1"
    scope: Namespaced
    names:
      plural: arithmeticoperations
      singular: arithmeticoperation
      kind: Arithmeticoperation
    validation:
      openAPIV3Schema:
        required: [ "spec" ]
        properties:
          spec:
            required: [ "firstNum","secondNum","operation" ]
            properties:
              firstNum:
                type: "int32"
              secondNum:
                type: "int32"
              operation:
                type: "string"
