/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "math-controller/pkg/apis/maths/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMathResources implements MathResourceInterface
type FakeMathResources struct {
	Fake *FakeMathsV1alpha1
	ns   string
}

var mathresourcesResource = schema.GroupVersionResource{Group: "maths.tatacommunications.com", Version: "v1alpha1", Resource: "mathresources"}

var mathresourcesKind = schema.GroupVersionKind{Group: "maths.tatacommunications.com", Version: "v1alpha1", Kind: "MathResource"}

// Get takes name of the mathResource, and returns the corresponding mathResource object, and an error if there is any.
func (c *FakeMathResources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MathResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mathresourcesResource, c.ns, name), &v1alpha1.MathResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MathResource), err
}

// List takes label and field selectors, and returns the list of MathResources that match those selectors.
func (c *FakeMathResources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MathResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mathresourcesResource, mathresourcesKind, c.ns, opts), &v1alpha1.MathResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MathResourceList{ListMeta: obj.(*v1alpha1.MathResourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.MathResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mathResources.
func (c *FakeMathResources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mathresourcesResource, c.ns, opts))

}

// Create takes the representation of a mathResource and creates it.  Returns the server's representation of the mathResource, and an error, if there is any.
func (c *FakeMathResources) Create(ctx context.Context, mathResource *v1alpha1.MathResource, opts v1.CreateOptions) (result *v1alpha1.MathResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mathresourcesResource, c.ns, mathResource), &v1alpha1.MathResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MathResource), err
}

// Update takes the representation of a mathResource and updates it. Returns the server's representation of the mathResource, and an error, if there is any.
func (c *FakeMathResources) Update(ctx context.Context, mathResource *v1alpha1.MathResource, opts v1.UpdateOptions) (result *v1alpha1.MathResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mathresourcesResource, c.ns, mathResource), &v1alpha1.MathResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MathResource), err
}

// Delete takes name of the mathResource and deletes it. Returns an error if one occurs.
func (c *FakeMathResources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mathresourcesResource, c.ns, name), &v1alpha1.MathResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMathResources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mathresourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MathResourceList{})
	return err
}

// Patch applies the patch and returns the patched mathResource.
func (c *FakeMathResources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MathResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mathresourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MathResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MathResource), err
}
