/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "math-controller/pkg/apis/mathresource/v1alpha1"
	scheme "math-controller/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MathResourcesGetter has a method to return a MathResourceInterface.
// A group's client should implement this interface.
type MathResourcesGetter interface {
	MathResources(namespace string) MathResourceInterface
}

// MathResourceInterface has methods to work with MathResource resources.
type MathResourceInterface interface {
	Create(ctx context.Context, mathResource *v1alpha1.MathResource, opts v1.CreateOptions) (*v1alpha1.MathResource, error)
	Update(ctx context.Context, mathResource *v1alpha1.MathResource, opts v1.UpdateOptions) (*v1alpha1.MathResource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MathResource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MathResourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MathResource, err error)
	MathResourceExpansion
}

// mathResources implements MathResourceInterface
type mathResources struct {
	client rest.Interface
	ns     string
}

// newMathResources returns a MathResources
func newMathResources(c *ArithmeticoperationsV1alpha1Client, namespace string) *mathResources {
	return &mathResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mathResource, and returns the corresponding mathResource object, and an error if there is any.
func (c *mathResources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MathResource, err error) {
	result = &v1alpha1.MathResource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mathresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MathResources that match those selectors.
func (c *mathResources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MathResourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MathResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mathresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mathResources.
func (c *mathResources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mathresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mathResource and creates it.  Returns the server's representation of the mathResource, and an error, if there is any.
func (c *mathResources) Create(ctx context.Context, mathResource *v1alpha1.MathResource, opts v1.CreateOptions) (result *v1alpha1.MathResource, err error) {
	result = &v1alpha1.MathResource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mathresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mathResource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mathResource and updates it. Returns the server's representation of the mathResource, and an error, if there is any.
func (c *mathResources) Update(ctx context.Context, mathResource *v1alpha1.MathResource, opts v1.UpdateOptions) (result *v1alpha1.MathResource, err error) {
	result = &v1alpha1.MathResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mathresources").
		Name(mathResource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mathResource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mathResource and deletes it. Returns an error if one occurs.
func (c *mathResources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mathresources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mathResources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mathresources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mathResource.
func (c *mathResources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MathResource, err error) {
	result = &v1alpha1.MathResource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mathresources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
